name: emo_rec
channels:
  - pykaldi
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _r-mutex=1.0.0=anacondar_1
  - _tflow_select=2.1.0=gpu
  - absl-py=0.11.0=pyhd3eb1b0_1
  - alabaster=0.7.12=py_0
  - astroid=2.5=py37h89c1867_1
  - astunparse=1.6.3=py_0
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - automat=20.2.0=py_0
  - babel=2.9.0=pyhd3deb0d_0
  - backcall=0.2.0=py_0
  - bcrypt=3.2.0=py37h7b6447c_0
  - binutils_impl_linux-64=2.33.1=he6710b0_7
  - binutils_linux-64=2.33.1=h9595d00_15
  - blas=1.0=openblas
  - bleach=3.3.0=pyh44b312d_0
  - blinker=1.4=py37h06a4308_0
  - brotlipy=0.7.0=py37h27cfd23_1003
  - bwidget=1.9.11=1
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2020.10.14=0
  - cachetools=4.2.1=pyhd3eb1b0_0
  - cairo=1.14.12=h8948797_3
  - certifi=2020.6.20=py37_0
  - cffi=1.14.0=py37h2e261b9_0
  - chardet=4.0.0=py37h06a4308_1003
  - click=7.1.2=pyhd3eb1b0_0
  - cloudpickle=1.6.0=py_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - constantly=15.1.0=py37h28b3542_0
  - cryptography=3.3.1=py37h3c74f83_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cudnn=7.6.5=cuda10.1_0
  - cupti=10.1.168=0
  - curl=7.69.1=hbc83047_0
  - cycler=0.10.0=py37_0
  - dbus=1.13.18=hb2f20db_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - docutils=0.16=py37h89c1867_3
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.2.10=he6710b0_2
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.4=h5ab3b9f_0
  - fribidi=1.0.10=h7b6447c_0
  - gast=0.3.3=py_0
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_15
  - gfortran_impl_linux-64=7.3.0=hdf63c60_1
  - gfortran_linux-64=7.3.0=h553295d_15
  - glib=2.63.1=h5a9c865_0
  - google-auth=1.21.3=py_0
  - google-auth-oauthlib=0.4.2=pyhd3eb1b0_2
  - google-pasta=0.2.0=py_0
  - graphite2=1.3.14=h23475e2_0
  - graphviz=2.40.1=h21bd128_2
  - grpcio=1.31.0=py37hf8bcb03_0
  - gsl=2.4=h14c3975_4
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_15
  - h5py=2.10.0=py37hd6299e0_1
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.6=hb1b8bf9_0
  - hyperlink=21.0.0=pyhd3eb1b0_0
  - icu=58.2=he6710b0_3
  - idna=2.10=pyhd3eb1b0_0
  - imagesize=1.2.0=py_0
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - incremental=17.5.0=py37_0
  - ipykernel=5.5.0=py37h888b3d9_1
  - ipython=7.19.0=py37hb070fc8_1
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - isort=5.7.0=pyhd8ed1ab_0
  - jedi=0.17.0=py37_0
  - jeepney=0.6.0=pyhd8ed1ab_0
  - jinja2=2.11.3=pyh44b312d_0
  - joblib=1.0.0=pyhd3eb1b0_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.11=pyhd8ed1ab_1
  - jupyter_core=4.7.1=py37h89c1867_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - keras=2.4.3=0
  - keras-base=2.4.3=py_0
  - keras-gpu=2.4.3=0
  - keras-preprocessing=1.1.0=py_1
  - keyring=22.0.1=py37h89c1867_0
  - kiwisolver=1.3.0=py37h2531618_0
  - krb5=1.17.1=h173b8e3_0
  - lazy-object-proxy=1.5.1=py37h4abf009_1
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libcurl=7.69.1=h20c2e04_0
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libllvm10=10.0.1=hbcb73fb_5
  - libopenblas=0.3.10=h5a2b251_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.13.0.1=hd408876_0
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - llvmlite=0.34.0=py37h269e1b5_4
  - lz4-c=1.9.3=h2531618_0
  - make=4.2.1=h1bed415_1
  - markdown=3.3.3=py37h06a4308_0
  - markupsafe=1.1.1=py37hb5d75c8_2
  - matplotlib=3.3.1=0
  - matplotlib-base=3.3.1=py37h817c723_0
  - mccabe=0.6.1=py_1
  - mistune=0.8.4=py37h4abf009_1002
  - nbclient=0.5.2=pyhd8ed1ab_0
  - nbconvert=6.0.7=py37h89c1867_3
  - nbformat=5.1.2=pyhd8ed1ab_1
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.4.3=pyhd8ed1ab_0
  - nomkl=3.0=0
  - numba=0.51.2=py37h04863e7_1
  - numpy=1.19.2=py37h6163131_0
  - numpy-base=1.19.2=py37h75fe3a5_0
  - numpydoc=1.1.0=py_1
  - oauthlib=3.1.0=py_0
  - olefile=0.46=py37_0
  - openblas=0.3.10=0
  - openblas-devel=0.3.10=0
  - openssl=1.1.1j=h27cfd23_0
  - opt_einsum=3.1.0=py_0
  - pandas=1.1.3=py37he6710b0_0
  - pandoc=2.11.4=h7f98852_0
  - pandocfilters=1.4.2=py_1
  - pango=1.42.4=h049681c_0
  - parso=0.8.1=pyhd3eb1b0_0
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.1.0=py37he98fc37_0
  - pip=20.2.4=py37_0
  - pixman=0.40.0=h7b6447c_0
  - prompt-toolkit=3.0.8=py_0
  - protobuf=3.13.0.1=py37he6710b0_1
  - psutil=5.7.3=py37hb5d75c8_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.8=py_0
  - pycodestyle=2.6.0=pyh9f0ad1d_0
  - pycparser=2.20=py_2
  - pydot=1.3.0=py37_0
  - pyflakes=2.2.0=pyh9f0ad1d_0
  - pygments=2.7.4=pyhd3eb1b0_0
  - pyhamcrest=2.0.2=py_0
  - pyjwt=1.7.1=py37_0
  - pykaldi=0.1.3=py37h14c3975_1
  - pylint=2.6.0=py37h89c1867_1
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyrsistent=0.17.3=py37h4abf009_1
  - pysocks=1.7.1=py37_1
  - python=3.7.7=hcf32534_0_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2020.5=pyhd3eb1b0_0
  - pyyaml=5.4.1=py37h27cfd23_1
  - pyzmq=20.0.0=py37h5a562af_1
  - qt=5.9.7=h5867ecd_1
  - qtawesome=1.0.2=pyhd8ed1ab_0
  - qtconsole=5.0.2=pyhd8ed1ab_0
  - qtpy=1.9.0=py_0
  - r-base=3.6.1=haffb61f_2
  - r-processx=3.3.0=r36h96ca727_0
  - r-ps=1.3.0=r36h96ca727_0
  - r-r6=2.4.0=r36h6115d3f_0
  - r-xopen=1.0.0=r36h6115d3f_0
  - readline=8.0=h7b6447c_0
  - requests=2.25.1=pyhd3eb1b0_0
  - requests-oauthlib=1.3.0=py_0
  - rope=0.18.0=pyh9f0ad1d_0
  - rsa=4.7=pyhd3eb1b0_1
  - scikit-learn=0.23.1=py37h7ea95a0_0
  - scipy=1.5.2=py37habc2bb6_0
  - seaborn=0.11.1=pyhd3eb1b0_0
  - secretstorage=3.3.1=py37h89c1867_0
  - service_identity=18.1.0=py37h28b3542_0
  - setuptools=52.0.0=py37h06a4308_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.15.0=py37h06a4308_0
  - snowballstemmer=2.1.0=pyhd8ed1ab_0
  - sphinx=3.5.1=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.4=py_0
  - spyder=3.3.5=py37_0
  - spyder-kernels=0.5.2=py37_0
  - sqlite=3.33.0=h62c20be_0
  - subprocess32=3.5.4=py_1
  - tbb=2020.3=hfd86e86_0
  - tensorboard=2.3.0=pyh4dce500_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.2.0=gpu_py37h1a511ff_0
  - tensorflow-base=2.2.0=gpu_py37h8a81be8_0
  - tensorflow-estimator=2.2.0=pyh208ff02_0
  - tensorflow-gpu=2.2.0=h0d30ee6_0
  - termcolor=1.1.0=py37_1
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - tktable=2.10=h14c3975_0
  - tornado=6.1=py37h27cfd23_0
  - traitlets=5.0.5=py_0
  - twisted=20.3.0=py37h7b6447c_0
  - typed-ast=1.4.1=py37h4abf009_1
  - urllib3=1.26.3=pyhd3eb1b0_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py_1
  - werkzeug=1.0.1=py_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - wrapt=1.12.1=py37h7b6447c_1
  - wurlitzer=2.0.1=py37h89c1867_1
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.3=h58526e2_3
  - zlib=1.2.11=h7b6447c_3
  - zope=1.0=py37_1
  - zope.interface=5.2.0=py37h27cfd23_0
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - apipkg==1.5
    - appdirs==1.4.4
    - audioread==2.1.8
    - contextlib2==0.6.0.post1
    - execnet==1.7.1
    - iniconfig==1.0.1
    - librosa==0.8.0
    - mock==4.0.2
    - packaging==20.4
    - path==15.0.0
    - path-py==12.5.0
    - pesq==0.0.2
    - pluggy==0.13.1
    - pooch==1.2.0
    - py==1.9.0
    - pydub==0.24.1
    - pyqt5==5.12.1
    - pyqt5-sip==4.19.19
    - pyqtwebengine==5.12.1
    - pystoi==0.3.3
    - pytest==6.1.1
    - pytest-shutil==1.7.0
    - python-speech-features==0.6
    - resampy==0.2.2
    - soundfile==0.10.3.post1
    - speechpy==2.4
    - toml==0.10.1
    - torch==1.7.1
    - torchaudio==0.7.2
    - torchvision==0.8.2
    - typing-extensions==3.7.4.3
    - zipp==3.3.0
prefix: /home/dsi/shvarta3/anaconda3/envs/emo_rec
